<?php if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die(); ?>
<?php

/**
 * @global CMain $APPLICATION
 */

?>
<?php $APPLICATION->IncludeComponent(
	"intec.universe:main.footer", 
	"template.1", 
	array(
		"SETTINGS_USE" => "Y",
		"PRODUCTS_VIEWED_SHOW" => "Y",
		"PRODUCTS_VIEWED_LAZYLOAD_USE" => "N",
		"REGIONALITY_USE" => "N",
		"CONTACTS_USE" => "Y",
		"CONTACTS_IBLOCK_TYPE" => "content",
		"CONTACTS_IBLOCK_ID" => "39",
		"CONTACTS_REGIONALITY_USE" => "Y",
		"CONTACTS_REGIONALITY_STRICT" => "N",
		"MENU_MAIN_ROOT" => "bottom",
		"MENU_MAIN_CHILD" => "left",
		"MENU_MAIN_LEVEL" => "4",
		"SEARCH_NUM_CATEGORIES" => "1",
		"SEARCH_TOP_COUNT" => "5",
		"SEARCH_ORDER" => "date",
		"SEARCH_USE_LANGUAGE_GUESS" => "Y",
		"SEARCH_CHECK_DATES" => "N",
		"SEARCH_SHOW_OTHERS" => "N",
		"SEARCH_INPUT_ID" => "footer-search",
		"SEARCH_TIPS_USE" => "N",
		"SEARCH_MODE" => "site",
		"LOGOTYPE_PATH" => "/include/logotype.intec.php",
		"LOGOTYPE_LINK" => "https://reklamafia.com/",
		"CONTACTS_PROPERTY_CITY" => "CITY",
		"CONTACTS_PROPERTY_ADDRESS" => "ADDRESS",
		"CONTACTS_PROPERTY_PHONE" => "PHONE",
		"CONTACTS_PROPERTY_EMAIL" => "EMAIL",
		"CONTACTS_PROPERTY_REGION" => "REGIONS",
		"PHONE_VALUE" => "+7 (000) 000 00 00",
		"PRODUCTS_VIEWED_IBLOCK_MODE" => "multi",
		"ADDRESS_VALUE" => "г. Калининград",
		"EMAIL_VALUE" => "admin@201086.ru",
		"COPYRIGHT_VALUE" => "&copy; #YEAR# Суши-бар kam-zu-mi",
		"FORMS_CALL_ID" => "1",
		"FORMS_CALL_TEMPLATE" => ".default",
		"SOCIAL_VK_LINK" => "https://vk.com/kamzumi",
		"SOCIAL_FACEBOOK_LINK" => "",
		"SOCIAL_INSTAGRAM_LINK" => "https://www.instagram.com/kam_zu_mi/",
		"SOCIAL_TWITTER_LINK" => "",
		"LOGOTYPE_SHOW" => "Y",
		"PHONE_SHOW" => "Y",
		"PRODUCTS_VIEWED_TITLE_SHOW" => "Y",
		"PRODUCTS_VIEWED_TITLE" => "Ранее вы смотрели",
		"PRODUCTS_VIEWED_PAGE_ELEMENT_COUNT" => "10",
		"PRODUCTS_VIEWED_COLUMNS" => "4",
		"PRODUCTS_VIEWED_SHOW_NAVIGATION" => "Y",
		"ADDRESS_SHOW" => "Y",
		"EMAIL_SHOW" => "N",
		"COPYRIGHT_SHOW" => "N",
		"FORMS_CALL_SHOW" => "N",
		"FORMS_CALL_TITLE" => "Заказать звонок",
		"MENU_MAIN_SHOW" => "Y",
		"SEARCH_SHOW" => "Y",
		"SOCIAL_SHOW" => "Y",
		"THEME" => "dark",
		"TEMPLATE" => "template.1",
		"ICONS" => array(
			0 => "ALFABANK",
			1 => "SBERBANK",
			2 => "QIWI",
			3 => "YANDEXMONEY",
			4 => "VISA",
			5 => "MASTERCARD",
			6 => "",
		),
		"CONSENT_URL" => "/company/consent/",
		"CATALOG_URL" => "/catalog/",
		"SEARCH_URL" => "/search/",
		"PRODUCTS_VIEWED_PRICE_CODE" => array(
			0 => "Kam-Zu-Mi",
		),
		"SEARCH_CATEGORY_0" => array(
			0 => "no",
		),
		"SEARCH_PRICE_CODE" => array(
			0 => "BASE",
		),
		"SEARCH_PRICE_VAT_INCLUDE" => "Y",
		"SEARCH_CURRENCY_CONVERT" => "N",
		"COMPONENT_TEMPLATE" => "template.1",
		"CONTACTS_ELEMENTS" => array(
			0 => "",
			1 => "",
		),
		"CONTACTS_ELEMENT" => "",
		"PRODUCTS_VIEWED_IBLOCK_TYPE" => "lists",
		"PRODUCTS_VIEWED_IBLOCK_ID" => "",
		"SOCIAL_YOUTUBE_LINK" => "",
		"SOCIAL_ODNOKLASSNIKI_LINK" => "",
		"PRODUCTS_VIEWED_CONVERT_CURRENCY" => "N",
		"PRODUCTS_VIEWED_SHOW_PRODUCTS_8" => "N",
		"PRODUCTS_VIEWED_SHOW_PRODUCTS_25" => "N",
		"SEARCH_CATEGORY_0_TITLE" => ""
	),
	false
); ?>